[rpc_endpoints]
op_chain_a = "http://127.0.0.1:9545"
op_chain_b = "http://127.0.0.1:9546"

[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
# ffi = true

fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='read-write', path='./deployment.json' },
  { access='read-write', path='./deployment-erc20.json' },
  { access='read-write', path='./deployment-erc4626.json' },
]

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
solady = "0.1.12"
solmate = "6.8.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
